name: GitHub Traffic Stats

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:      # allow manual runs

jobs:
  get-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch traffic stats for all repos
        run: |
          echo "# GitHub Traffic Stats" > TRAFFIC.md
          REPOS=("tediyo/repo1" "tediyo/repo2" "tediyo/repo3") # list your repos here
          
          for repo in "${REPOS[@]}"
          do
            echo "## $repo" >> TRAFFIC.md
            curl -s -H "Accept: application/vnd.github+json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 https://api.github.com/repos/$repo/traffic/views \
                 | jq '. | "Total Views: \(.count), Unique Visitors: \(.uniques)"' >> TRAFFIC.md
            echo "" >> TRAFFIC.md
          done

      - name: Commit & Push updated stats
        run: |
         git config --local user.name "github-actions[bot]"
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add TRAFFIC.md
         git diff --staged --quiet || git commit -m "chore: update traffic stats"
         git remote set-url origin https://tediyo:${{ secrets.G-Stat-PAT }}@github.com/tediyo/G-Stats.git
         git push origin HEAD:main

