name: GitHub Traffic Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch traffic stats for all repos
        run: |
          echo "# GitHub Traffic Stats" > TRAFFIC.md
          REPOS=(
            "tediyo/Enkutatash-Gift-Card-New-Year"
            "tediyo/E-Store-for-EST"
            "tediyo/tediyo"
            "tediyo/New-Portfolio"
            "tediyo/E-Shop-MC-Foundation-back-services"
            "tediyo/Portfolio-Template"
            "tediyo/Enkutatash-Gift-Card"
            "tediyo/Weather-App"
            "tediyo/tediyo.github.io"
            "tediyo/Simple-Calculator"
            "tediyo/React-Weather-App"
            "tediyo/React-E-Commerce"
            "tediyo/E-Store"
            "tediyo/React-To-Do-App"
            "tediyo/React-Portfolio"
            "tediyo/E-Commerce-App"
            "tediyo/Enkutatash"
            "tediyo/React-Movie-App"
            "tediyo/E-Shop"
            "tediyo/E-Commerce-Store"
            "tediyo/React-Redux-Store"
            "tediyo/React-Blog"
            "tediyo/React-Admin-Panel"
            "tediyo/React-Chart"
            "tediyo/React-Login"
            "tediyo/React-Register"
            "tediyo/React-Profile"
            "tediyo/React-Dashboard"
            "tediyo/React-Product"
            "tediyo/React-Cart"
            "tediyo/React-Checkout"
            "tediyo/React-Order"
          )
          for repo in "${REPOS[@]}"
          do
            echo "## $repo" >> TRAFFIC.md
            curl -s -H "Accept: application/vnd.github+json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 https://api.github.com/repos/$repo/traffic/views \
                 | jq '. | "Total Views: \(.count), Unique Visitors: \(.uniques)"' >> TRAFFIC.md
            echo "" >> TRAFFIC.md
          done

      - name: Commit & Push updated stats
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add TRAFFIC.md
          git diff --staged --quiet || git commit -m "chore: update traffic stats"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tediyo/G-Stats.git HEAD:main
